# Apply this yaml to "monitoring" namespace

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: monitoring
  name: faas-prometheus--recording.rules
spec:
  groups:
  - name: faas-prometheus--recording.rules
    rules:
      - record: faas_http_request_rate
        expr: sum by(application, uri, status) (label_replace(rate(http_server_requests_seconds_count{uri !="/actuator/prometheus"}[5m]), "status", "${1}xx", "code", "([0-9]).."))

      - record: faas_node_filesystem_free_percent
        expr: 100 * node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}  


---

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: monitoring
  name: faas-prometheus-alertmanager.rules
spec:
  groups:
  - name: faas-prometheus-alertmanager.rules
    rules:
    - alert: HighApplicationErrorRate
      annotations:
        description: 'Applicaton: {{ $labels.application}} is experiencing high error rate of: {{ $value }}'
        summary: High Application Error Rate
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-errorbudgetburn
      expr: faas_http_request_rate{status="500"} > 1
      for: 1m
      labels:
        severity: warning
